spring:
  application:
    name: ${APP_NAME}

  cors:
    originPatterns: ${CORS_ORIGINS}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${SHOW_SQL}

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  flyway:
    repair-on-migrate: true
    clean-disabled: false
    clean-before-validation: true

# CONFIGURAÇÕES DE ARQUIVOS EXTERNOS
file:
  upload-dir: ${UPLOAD_PATH_BASE}
  upload-dir-txt: ${UPLOAD_PATH_TXT}
  upload-dir-pdf: ${UPLOAD_PATH_PDF}
  upload-dir-video: ${UPLOAD_PATH_VIDEO}
  upload-dir-song: ${UPLOAD_PATH_SONG}
  upload-dir-Other: ${UPLOAD_PATH_OTHER}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    br.com.jzbreno: ${LOG_LEVEL_APP:DEBUG}